rt_bi_emulator:
  av1:
    ros__parameters:
      render: True
      id: "https://rezateshnizi.com/env/defintion/av1"
      updateInterval: 0.75
      timesSecs:
        - 0.0
        - 120.0
      cutOffTime: inf
      centersOfRotation:
        - "[1500, 1000.0]"
        - "[1500, 1000.0]"
      polygons:
        - "[[1250.0, -100.0], [1750.0, -100.0], [1750.0, 1100.0], [1250.0, 1100.0]]"
        - "[[1250.0, -100.0], [1750.0, -100.0], [1750.0, 1100.0], [1250.0, 1100.0]]"
