rt_bi_emulator:
  av1:
    ros__parameters:
      render: True
      id: "https://rezateshnizi.com/ex2-map/defintion/av1"
      updateInterval: 0.75
      timesSecs:
        - 0.0
        - 120.0
      cutOffTime: inf
      centersOfRotation:
        - "[2687.5, 1625.0]"
        - "[2687.5, 1625.0]"
      polygons:
        - "[[2600.0, 1550.0], [2775.0, 1550.0], [2775.0, 1700.0], [2600.0, 1700.0]]"
        - "[[2600.0, 1550.0], [2775.0, 1550.0], [2775.0, 1700.0], [2600.0, 1700.0]]"
