PREFIX class:    <https://rezateshnizi.com/rt-bi-v2/class#>
PREFIX property: <https://rezateshnizi.com/rt-bi-v2/property#>
PREFIX target:   <https://rezateshnizi.com/env/targets#>

INSERT {
	target:# TOKEN_ID # a class:Target ;
		property:name         "# TOKEN_NAME #" ;
		property:derived_from target:# PARENT_ID # ;
		property:target_category ?cat .
}
WHERE {
	VALUES ?cat { # SURVIVING_CATEGORY_IRIS # }
}
