PREFIX class:    <https://rezateshnizi.com/rt-bi-v2/class#>
PREFIX dc:       <http://purl.org/dc/elements/1.1/>
PREFIX interval: <https://rezateshnizi.com/env/intervals#>
PREFIX material: <https://rezateshnizi.com/env/materials#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX polygon:  <https://rezateshnizi.com/env/polys#>
PREFIX pt:       <https://rezateshnizi.com/env/pts#>
PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX set:      <https://rezateshnizi.com/env/sets#>
PREFIX property: <https://rezateshnizi.com/rt-bi-v2/property#>
PREFIX t:        <https://rezateshnizi.com/env/ts#>
PREFIX target:   <https://rezateshnizi.com/env/targets#>
PREFIX x:        <https://rezateshnizi.com/env/xs#>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>
PREFIX y:        <https://rezateshnizi.com/env/ys#>

INSERT DATA {
	# TARGET_TRIPLES ############################
}
