PREFIX property: <https://rezateshnizi.com/rt-bi-v2/property#>
PREFIX target:   <https://rezateshnizi.com/env/targets#>

SELECT ?target
	# SELECT ####################################
WHERE {
	VALUES ?target {
		# ID VALUES #############################
	}
	# WHERE #####################################
}
GROUP BY ?target
	# GROUP_BY ##################################
