?start: expression

?expression:	simple_expression
			| negated_expression
			| ("(" expression ")")
			| (expression connector expression)

negated_expression: NOT simple_expression

connector: AND | OR

simple_expression: property_seq test value

property_seq: VARIABLE ("." VARIABLE)*

test: EQ | NEQ | INCLUDES | IN | LTE | GTE

value:	_boolean
		| ESCAPED_STRING
		| NUMBER
		| range_value

range_value: "[" NUMBER "," NUMBER "]"

_boolean: TRUE | FALSE

EQ:			"=="
NEQ:		"!="
AND:		"AND"
OR:			"OR"
NOT:		"NOT"
INCLUDES:	"INCLUDES"
IN:			"IN"
LTE:		"<="
GTE:		">="

TRUE:		"true"
FALSE:		"false"

%import common.CNAME -> VARIABLE
%import common.NUMBER
%import common.WS_INLINE
%import common.ESCAPED_STRING

%ignore WS_INLINE
