rt_bi_runtime:
  dd_rdf_1:
    ros__parameters:
      fuseki_server: "http://192.168.1.76:8090"
      rdf_store: "rt-bi-v2-1"
      rdf_dir: "rdf" # Don't forget to add the resource directories to setup.py
      sparql_dir: "sparql" # Don't forget to add the resource directories to setup.py
      sparql_dir_operators: "operators"
      sparql_channel: "channel.rq"
      sparql_geometry: "geometry.rq"
      sparql_insert: "insert.rq"
      sparql_intervals: "intervals.rq"
      sparql_sets: "sets.rq"
      sparql_targets: "targets.rq"
      sparql_aggregation_operators: "aggregation_operators.rq"
      placeholder_bind: "# BIND ######################################"
      placeholder_ids: "# ID VALUES #############################"
      placeholder_insert: "# INSERT VALUES #############################"
      placeholder_order: "# ORDER #####################################"
      placeholder_select: "# SELECT ####################################"
      placeholder_where: "# WHERE #####################################"
      placeholder_group_by: "# GROUP_BY ##################################"
      placeholder_filter_traversability: "# FILTER_TRAVERSABILITY #####################"
      placeholder_prop_uri: "# PROP_URI #"
      placeholder_out_var: "# OUT_VAR #"
      markup_select_fragment: "# SELECT_FRAGMENT ##############"
      markup_group_by_fragment: "# GROUP_BY_FRAGMENT ############"
      markup_where_fragment: "# WHERE_FRAGMENT ###############"
      transition_grammar_dir: "rdf" # Don't forget to add the resource directories to setup.py
      transition_grammar_file: "transition.lark"
